{ config, pkgs, inputs, ... }:

let
  tailscale-home = pkgs.writeShellApplication {
    name = "tailscale-home";
    runtimeInputs = [ pkgs.tailscale ];
    text = builtins.readFile ../../scripts/tailscale-home.sh;
  };

  tailscale-protect = pkgs.writeShellApplication {
    name = "tailscale-protect";
    runtimeInputs = [ pkgs.tailscale ];
    text = builtins.readFile ../../scripts/tailscale-protect.sh;
  };

  tailscale-autoswitch = pkgs.writeShellApplication {
    name = "tailscale-autoswitch";
    runtimeInputs = [
      pkgs.iw
      pkgs.iproute2
      pkgs.coreutils
      pkgs.gnugrep
      pkgs.gnused
      tailscale-home
      tailscale-protect
    ];
    text = builtins.readFile ../../scripts/tailscale-autoswitch.sh;
  };

  vpn-status = pkgs.writeShellApplication {
    name = "vpn-status";
    runtimeInputs = [ pkgs.curl pkgs.tailscale pkgs.gnugrep ];
    text = builtins.readFile ../../scripts/vpn-status.sh;
  };

  taillog = pkgs.writeShellApplication {
    name = "taillog";
    runtimeInputs = [ pkgs.coreutils ];
    text = builtins.readFile ../../scripts/taillog.sh;
  };
in
{
  imports = [
    # Hardware configuration is auto-generated by the installer
    ./hardware-configuration.nix
  ];

  # Network Mount: piCloud SMB share on Pi5
  fileSystems."/home/kyle/piCloud" = {
    device = "//100.73.97.16/piCloud";
    fsType = "cifs";
    options = [
      "credentials=/home/kyle/.smbcredentials"
      "uid=1000"
      "gid=100"
      "x-systemd.automount"
      "noauto"
      "_netdev"
      "x-systemd.idle-timeout=60"
      "x-systemd.mount-timeout=5s" # Limit mount/unmount wait time during state change
      "soft"                      # Return error on connection loss instead of hanging kernel
    ];
  };

  # Bootloader configurations
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelParams = [ "zswap.enabled=0" "quiet" "splash" ];
  boot.plymouth.enable = true;
  boot.zfs.forceImportRoot = false;

  # Enable ARM64 emulation for building Raspberry Pi images
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  # Load Nvidia drivers in initrd (Early KMS) to prevent GDM race conditions / black screen hangs
  boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];

  boot.extraModprobeConfig = ''
    options nvidia NVreg_EnableGpuFirmware=0
  '';

  # Networking
  networking.hostName = "nixMitters";
  networking.networkmanager.enable = true;

  # Time Zone and Locale
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";

  # Enable Graphics and Nvidia drivers
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = true;
    powerManagement.finegrained = true;
    open = false; # Set to true if GPU is Turing or newer and you prefer open-source drivers
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;

    # Configure Prime Offloading (Hybrid Mode)
    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  # Enable the GNOME Desktop Environment (using GDM display manager)
  services.xserver.enable = true;
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;

  # Commented out COSMIC Desktop Environment for reference:
  # services.desktopManager.cosmic.enable = true;
  # services.displayManager.cosmic-greeter.enable = true;

  # Audio (Pipewire)
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # User Accounts
  users.users.kyle = {
    isNormalUser = true;
    description = "Kyle";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    shell = pkgs.bash;
  };

  # Passwordless Sudo for wheel group members
  security.sudo.wheelNeedsPassword = false;

  # Services
  services.resolved.enable = true;
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "client";
  };
  services.flatpak.enable = true;
  services.openssh.enable = true;

  # Enable zram Swap to prevent OOM crashes during heavy R compilation
  zramSwap.enable = true;

  # Force Nix daemon to build in /var/tmp (SSD) instead of /tmp (RAM disk)
  systemd.services.nix-daemon.environment.TMPDIR = "/var/tmp";

  # Hardware Udev Rules for NuPhy keyboard
  services.udev.extraRules = ''
    # Rules for NuPhy keyboard config (WebHID)
    KERNEL=="hidraw*", ATTRS{idVendor}=="19f5", ATTRS{idProduct}=="1028", MODE="0666", GROUP="plugdev", TAG+="uaccess"
  '';

  # Bluetooth support
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Thunderbolt support
  services.hardware.bolt.enable = true;

  # Responsiveness & Process Tuning
  services.ananicy = {
    enable = true;
    package = pkgs.ananicy-cpp;
  };

  # NetworkManager Dispatcher Scripts
  networking.networkmanager.dispatcherScripts = [
    {
      source = pkgs.writeText "99-tailscale-autoswitch" ''
        #!/usr/bin/env bash
        case "$2" in
            up)
                ${tailscale-autoswitch}/bin/tailscale-autoswitch &
                ;;
        esac
      '';
      type = "basic";
    }
  ];

  # Fonts
  fonts.packages = with pkgs; [
    google-sans
  ];
  
  services.syncthing = {
    enable = true;
    user = "kyle";
    dataDir = "/home/kyle";
    configDir = "/home/kyle/.local/state/syncthing";
    openDefaultPorts = true;
    overrideDevices = true;
    overrideFolders = true;
    settings = {
      devices = {
        "nixMitters" = { id = "4M2NBJI-EZDAG3P-5UFM3AM-YWBX3E3-T6CNBYM-O6QLNKM-7QYEYXD-MFAY2AM"; };
        "nixPi5" = { id = "HR7M54M-7UPVYDD-UNJUJAJ-QH4QOZI-UHV6HM4-HW66Z7A-D7KAPXO-LGZYCA5"; };
        "windowsMitters" = { id = "PFYTBDZ-PLXFXTJ-UGOIKCR-RR3LZZB-4BQBNSH-QZWOGFR-AFWZ2QP-3GRRRAP"; };
        "UH-JCX0TV3" = { id = "52ZVBSB-QSFLLK3-MWYTJF5-QQIFTFG-MQWJGRE-IBXO6TA-WLLU57F-U57Y4QZ"; };
      };
      folders = {
        "claude-home" = {
          path = "/home/kyle/.claude";
          devices = [ "nixPi5" "UH-JCX0TV3" ];
          ignorePerms = true;
        };
        "gemini-cli" = {
          path = "/home/kyle/.gemini";
          devices = [ "nixPi5" "UH-JCX0TV3" ];
          ignorePerms = true;
        };
        "kyle-claude-projects" = {
          path = "/home/kyle/.claude/projects";
          devices = [ "nixPi5" "UH-JCX0TV3" ];
          ignorePerms = true;
        };
        "kyle-compiler" = {
          path = "/home/kyle/dev/agentic-memory-compiler";
          devices = [ "nixPi5" "windowsMitters" ];
          ignorePerms = true;
        };
        "obsidian" = {
          path = "/home/kyle/Documents/obsidian";
          devices = [ "nixPi5" "windowsMitters" ];
          ignorePerms = true;
        };
      };
    };
  };

  # Stop CIFS automount and unmount share on suspend to prevent kernel freezes, restart on resume
  systemd.services.cifs-suspend-handler = {
    description = "Stop CIFS automount and unmount share on suspend, restart on resume";
    before = [ "sleep.target" ];
    wantedBy = [ "sleep.target" ];
    unitConfig.StopWhenUnneeded = true;
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "cifs-pre-suspend" ''
        ${pkgs.systemd}/bin/systemctl stop home-kyle-piCloud.automount
        ${pkgs.util-linux}/bin/umount -l /home/kyle/piCloud || true
      '';
      ExecStop = pkgs.writeShellScript "cifs-post-resume" ''
        ${pkgs.systemd}/bin/systemctl start home-kyle-piCloud.automount
      '';
    };
  };

  # Virtualization
  virtualisation.docker.enable = true;

  # Enable nix-ld to run unpatched dynamic binaries (like agy and claude)
  programs.nix-ld.enable = true;

  # Nix Settings (Enable Flakes and Optimize Store)
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
    max-jobs = 4;
    cores = 2;
    substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"
      "https://nixos-raspberrypi.cachix.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      "nixos-raspberrypi.cachix.org-1:4iMO9LXa8BqhU+Rpg6LQKiGa2lsNh/j2oiYLNOQ5sPI="
    ];
  };

  # System-wide Packages (Keep this minimal, most go to Home Manager)
  environment.systemPackages = with pkgs; [
    git
    micro
    curl
    wget
    cifs-utils       # Required for SMB/piCloud mounts
    iw               # Required for WiFi SSID detection in autoswitch script
    iproute2         # Required for ip link check in autoswitch script
    docker-compose   # Container orchestration helper
    
    # Declarative Tailscale switcher utilities
    tailscale-autoswitch
    tailscale-home
    tailscale-protect
    vpn-status
    taillog

  ];

  # Allow Unfree Packages (needed for Nvidia, Positron, etc.)
  nixpkgs.config.allowUnfree = true;

  # NixOS State Version (Do not change this, matches installation target)
  system.stateVersion = "26.05";
}
