{ config, pkgs, inputs, ... }:

{
  imports = [
    # Hardware configuration is auto-generated by the installer
    ./hardware-configuration.nix
  ];

  # Network Mount: piCloud SMB share on Pi5
  fileSystems."/home/kyle/piCloud" = {
    device = "//100.73.97.16/piCloud";
    fsType = "cifs";
    options = [
      "credentials=/home/kyle/.smbcredentials"
      "uid=1000"
      "gid=100"
      "x-systemd.automount"
      "noauto"
      "_netdev"
      "x-systemd.idle-timeout=60"
    ];
  };

  # Bootloader configurations
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelParams = [ "zswap.enabled=0" ];
  boot.extraModprobeConfig = ''
    options nvidia NVreg_EnableGpuFirmware=0
  '';

  # Networking
  networking.hostName = "nixMitters";
  networking.networkmanager.enable = true;

  # Time Zone and Locale
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";

  # Enable Graphics and Nvidia drivers
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false; # Set to true if GPU is Turing or newer and you prefer open-source drivers
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Enable the GNOME Desktop Environment (using GDM display manager)
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # Commented out COSMIC Desktop Environment for reference:
  # services.desktopManager.cosmic.enable = true;
  # services.displayManager.cosmic-greeter.enable = true;

  # Audio (Pipewire)
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # User Accounts
  users.users.kyle = {
    isNormalUser = true;
    description = "Kyle";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    shell = pkgs.bash;
  };

  # Passwordless Sudo for wheel group members
  security.sudo.wheelNeedsPassword = false;

  # Services
  services.resolved.enable = true;
  services.tailscale.enable = true;
  services.flatpak.enable = true;
  services.openssh.enable = true;

  # Hardware Udev Rules for NuPhy keyboard
  services.udev.extraRules = ''
    # Rules for NuPhy keyboard config (WebHID)
    KERNEL=="hidraw*", ATTRS{idVendor}=="19f5", ATTRS{idProduct}=="1028", MODE="0666", GROUP="plugdev", TAG+="uaccess"
  '';

  # Bluetooth support
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Thunderbolt support
  services.hardware.bolt.enable = true;

  # Responsiveness & Process Tuning
  services.ananicy = {
    enable = true;
    package = pkgs.ananicy-cpp;
  };

  # NetworkManager Dispatcher Scripts
  networking.networkmanager.dispatcherScripts = [
    {
      source = pkgs.writeText "99-tailscale-autoswitch" ''
        #!/usr/bin/env bash
        case "$2" in
            up)
                /home/kyle/.local/bin/tailscale-autoswitch &
                ;;
        esac
      '';
      type = "basic";
    }
  ];

  # Fonts
  fonts.packages = with pkgs; [
    google-sans
  ];
  
  services.syncthing = {
    enable = true;
    user = "kyle";
    dataDir = "/home/kyle";
    configDir = "/home/kyle/.config/syncthing";
  };

  # Virtualization
  virtualisation.docker.enable = true;

  # Enable nix-ld to run unpatched dynamic binaries (like agy and claude)
  programs.nix-ld.enable = true;

  # Nix Settings (Enable Flakes and Optimize Store)
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  # System-wide Packages (Keep this minimal, most go to Home Manager)
  environment.systemPackages = with pkgs; [
    git
    micro
    curl
    wget
    cifs-utils       # Required for SMB/piCloud mounts
    iw               # Required for WiFi SSID detection in autoswitch script
    iproute2         # Required for ip link check in autoswitch script
    docker-compose   # Container orchestration helper
  ];

  # Allow Unfree Packages (needed for Nvidia, Positron, etc.)
  nixpkgs.config.allowUnfree = true;

  # NixOS State Version (Do not change this, matches installation target)
  system.stateVersion = "26.05";
}
